name: graphql_flutter_henry_fork
description: A GraphQL client for Flutter.
version: 0.8.1
authors:
  - Eus Dima <eus@zinoapp.com>
  - Zino Hofmann <zino@zinoapp.com>
homepage: https://github.com/zino-app/graphql-flutter

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.0
  path_provider: ^0.4.0
  uuid: ^1.0.0
  test: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=2.0.0-dev.52.0 <3.0.0"
